version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dingo
      MYSQL_DATABASE: mysms
    ports:
      - "3306:3306"
  app:
    build: .
    command: tail -f /dev/null
    environment:
      DB_HOST: db
      DB_PWD: dingo
      DB_USER_NAME: root
      DB_PORT: 3306
    volumes:
      - .:/mysms
      - /mysms/node_modules
    ports: 
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
